In [1]:
import numpy as np
import gdal
import os 
import time
%matplotlib inline

### Read raster data in Python

In [50]:
# Using gdal library to read raster data
path=r"F:\Training_Material\Test"

img=gdal.Open(os.path.join(path,"Landcover.tif"))
# Read raster as array numpy
np_array=img.ReadAsArray().astype("int32")

In [51]:
def xulynegative(x):
    if x-7<0:
        return 0
    else:
        return x-7

def xulypositive(x,xmax):
    if x+7>xmax:
        return xmax
    else:
        return x+7

def get_pixel_datlua(unique,counts):
    zip_iterator=zip(list(unique),list(counts))
    mydict=dict(zip_iterator)
    return mydict[1]

In [69]:
start_time = time.time()
numpy_result = np.full(np_array.shape,1.0000)

for x in range(len(np_array)):
    for y in range(len(np_array[x])):
     
        if np_array[x,y] ==0:
            pass
        else:
            xmax,ymax = np_array.shape
            subset = np_array[xulynegative(x):xulypositive(x,xmax),xulynegative(y):xulypositive(y,ymax)]
            unique, counts = np.unique(subset,return_counts=True)
            try:
                ketqua = get_pixel_datlua(unique, counts)/subset.size
            except:
                ketqua = 0

            numpy_result[x,y] = ketqua
print("--- %s seconds ---" % (time.time() - start_time))

--- 4.476495742797852 seconds ---


In [70]:
fn = r'F:\Training_Material\Test\Rice_200m.tif'
driver = gdal.GetDriverByName('GTiff')
ds = driver.Create(fn, xsize=np_array.shape[1], ysize=np_array.shape[0], bands=1, eType=gdal.GDT_Float32)
ds.GetRasterBand(1).WriteArray(numpy_result)
ds.SetGeoTransform(img.GetGeoTransform())
ds.SetProjection(img.GetProjection())
ds = None

In [66]:
numpy_result

array([[1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1],
       ...,
       [1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1],
       [1.1, 1.1, 1.1, ..., 1.1, 1.1, 1.1]])

In [7]:
mynp=np.array([[1,2,3,4],[3,4,5,6]])

In [46]:
len(mynp)

2

In [34]:
unique,counts = np.unique(mynp,return_counts=True)

In [36]:
counts

array([1, 1, 2, 2, 1, 1], dtype=int64)

In [14]:
np.full(mynp.shape,-9999)

array([[-9999, -9999, -9999, -9999],
       [-9999, -9999, -9999, -9999]])

In [37]:
zip_iterator=zip(list(unique),list(counts))
mydict=dict(zip_iterator)

In [38]:
zip_iterator

In [40]:
mydict

{1: 1, 2: 1, 3: 2, 4: 2, 5: 1, 6: 1}